CodeSquad-2023-BE-Study/Algorithm-Study

.gitmessage.txt, HyowonSin/Week_01/BOJ_1018_체스판다시칠하기.java, HyowonSin/Week_01/BOJ_1051_숫자정사각형.java, HyowonSin/Week_01/BOJ_1065_한수.java, HyowonSin/Week_01/BOJ_2231_분해합.java, HyowonSin/Week_01/BOJ_2309_일곱난쟁이.java
=> [Week 01] 5문제 제출합니다.

HyowonSin/Week_02/BOJ_10814_나이순정렬.java, HyowonSin/Week_02/BOJ_11650_좌표정렬하기.java, HyowonSin/Week_02/BOJ_1946_신입사원.java, HyowonSin/Week_02/BOJ_2752_세수정렬.java, HyowonSin/Week_02/BOJ_5576_콘테스트.java
제출이 늦어서 죄송합니다 ㅜㅜ
신입 사원 문제에서
처음에 순위가 아닌 점수로 착각해서 문제 이해가 오래 걸렸습니다.
풀긴 했는데 시간 초과가 났습니다.
원인은 버퍼가 마지막 줄을 읽지 않아서
for 문이 멈춥니다.
(엔터를 한번 씩 쳐줘야 넘어가요)
왜 그런지는 모르겠네요.. ㅠㅠ
다음 주차 부터는 미리 미리 제출하겠습니다..
벌금도 내겠습니다..
=> [Week 02] 5문제 제출합니다. (1문제 시간 초과)

JeonHyoChang/week_03/BOJ_1072_게임.py, JeonHyoChang/week_03/BOJ_1920_수찾기.py, JeonHyoChang/week_03/BOJ_2417_정수제곱근.py, JeonHyoChang/week_03/BOJ_2805_나무자르기.py, JeonHyoChang/week_03/BOJ_6236_용돈관리.py
- 문제를 보고서 바로 이분 탐색을 적용해야 겠다는 생각을 빠르게 하지 못한점이 너무 아쉬웠습니다. 문제를 많이 풀어서 빨리 적응해야 할듯 합니다. 😭
- 문제를 제출하고 한번에 통과를 못하는 경우가 많았습니다. 아직 이분탐색을 다루는게 미흡 하고, 백준 변태같은 테스트 케이스가 원망스럽습니다 ㅋㅋㅋㅋ
- 자바로 구현시 변수 범위를 생각하거나 속도를 신경 써야하는데 파이썬으로 고민 해결!! (파이썬 최고👍🏼)
- 매주 문제를 표시할때 `문제 유형`을 가리는건 어떤가 하는 생각을 했습니다. 너무 큰 힌트 같아서 ㅋㅋ;;;
- 큰 틀은 다음과 같은 방식으로 진행
> ```python
> while start <= end:
>     mid = (start + end) // 2
>     if 조건:
>         start = mid + 1
>     else:
>         end = mid - 1
> ```
- 문제별 필요한 조건을 식으로 작성 or 함수 구현
- 포로의 리드미 작성을 보고 또한번 배워 갑니다 역시 `포갓🌞`
- 최대한 빠르게 이분탐색 이라고 분류 하는 느낌(?)은 다음과 같이 느꼈습니다.
- 1. 제한 시간을 확인한다.
- 2. 일단 제출한다. -> 시간 초과 시 이분탐색으로 다시 푼다 ㅠ
- 3. 그냥 원천 차단하자(시간 복잡도를 고려해서 처음부터 설계한다.)
- 파이썬의 경우 자료형의 범위를 신경쓰지 않아도 되고, 함수형태로 표현하는 방식이 너무 간결합니다.
- ➕ 리스트의 관리가 매우 쉽고, 따로 import 추가 안하고 기본 제공 기능 선에서 처리가능한 문제가 많습니다.
- …
=> [Week 03] 백준 이분탐색 알고리즘 - 5문제 제출

jinny-l/week_04/BOJ_11728_배열_합치기.java, jinny-l/week_04/BOJ_1940_주몽.java, jinny-l/week_04/BOJ_2531_회전_초밥.java, jinny-l/week_04/BOJ_3273_두_수의_합.java
안녕하세요, Jinny입니다.
이번주는 옵션 문제는 제외하고 제출합니다.
욕심같아서 다 풀고 싶은데 전주부터 밀린 것이 있어서 스케줄 관리가 안되네요 🥲
일단 알고리즘을 모른채로 문제를 풀어봤는데 `두 수의 합` 문제 제외하고는 풀렸습니다.
두 수의 합 문제를 풀면서 [블로그](https://velog.io/@isohyeon/Java-%EB%B0%B1%EC%A4%80-1940-%EC%A3%BC%EB%AA%BD%EC%9D%98-%EB%AA%85%EB%A0%B9)를 참고하여 풀었습니다.
그리고 문제를 다시 봤는데 주몽은 투포인터인 것이 확실히 보였고,
배열 합치기랑 회전 초밥 문제는 투 포인터 문제라고 명시되어 있지 않다면 애매하게 느껴졌습니다.
=> [Week 04] 백준 두포인터 알고리즘 - 4문제 완료

Gwonwoo-Nam/week_04/BOJ_11728_배열합치기.java, Gwonwoo-Nam/week_04/BOJ_1940_주몽.java, Gwonwoo-Nam/week_04/BOJ_2118_두개의탑.java, Gwonwoo-Nam/week_04/BOJ_2531_회전초밥.java, Gwonwoo-Nam/week_04/BOJ_3273_두수의합.java
개념은 단순한데 문제에 적용하려니 어려웠던 것 같습니다. 
이번주에 너무 바빴어서 빨리 푸느라 주석이 없습니다..ㅠ
주몽 문제랑 두수의 합은 입력 위치만 바꾸니 똑같이 정답처리되더라구요 ㅎ
회전초밥, 두개의 탑 문제는 시간초과때문에 까다로웠는데 불필요한 반복을 줄이기가 쉽지 않았습니다.
힌트를 살짝 얻어서 풀었습니다 ㅎ
=> [Week 04] 백준 두포인터 알고리즘 - 5문제 완료

jaea-kim/week_04/BOJ_11728_배열합치기.java, jaea-kim/week_04/BOJ_1940_주몽.java, jaea-kim/week_04/BOJ_2118_두개의탑.java, jaea-kim/week_04/BOJ_2531_회전초밥.java, jaea-kim/week_04/BOJ_3273_두수의합.java
이번 주말 몸 상태가 좋지 않아서 문제를 다 풀지 못했습니다. 
죄송합니다.. 다음 주 모임 때 제가 커피 사겠습니다. 
내일 좋은 상태로 마무리해서 제출하고 코멘트 추가 하겠습니다.
=> [Week 04] 백준 두포인터 알고리즘 - 3문제 완료 + 1문제 완료, 1문제 시간초과

Gwonwoo-Nam/week_05/BOJ_1012_유기농배추.java, Gwonwoo-Nam/week_05/BOJ_11724_연결요소의개수.java, Gwonwoo-Nam/week_05/BOJ_1260_DFS와BFS.java, Gwonwoo-Nam/week_05/BOJ_2606_바이러스.java, Gwonwoo-Nam/week_05/BOJ_7576_토마토.java
DFS, BFS 문제는 list로 만든다음에 comparator로 정렬한 후 탐색했는데 정렬에서 문제가 있었는지
자꾸 오답이 떠서 인접행렬로 바꿔서 풀었더니 Pass했습니다.
주석도 제대로 못달고 시간이 없었는데 다음 주에는 미리미리해보겠습니다 ㅎ..
=> [Week05] BOJ 그래프 탐색 알고리즘 - 5문제 완료 BFS, DFS

jaea-kim/week_05/BOJ_1012_유기농배추.java, jaea-kim/week_05/BOJ_11724_연결요소의개수.java, jaea-kim/week_05/BOJ_1260_DFS와BFS.java, jaea-kim/week_05/BOJ_2606_바이러스.java, jaea-kim/week_05/BOJ_7576_토마토.java
이번 주제는 BFS와 DFS에 대해 먼저 공부를 하고 진행하였습니다.  
그래서인지 생각보다는 쉽게 접근할 수 있었습니다. 다른 방식은 아예 고려하지 않고 처음부터 dfs나 bfs로 풀겠다고 생각하고 접근했기 때문이죠....ㅎㅎ
그래프를 인접 행렬, 인접 리스트로 표현할 수 있다고 하는데 저는 행렬이 편하게 느껴서 이번 문제 전부 행령 방식으로 표현하여 구현하였습니다. 
가장 오래 고민하며 풀었던 문제는 `토마토`였고 그래프 문제는 dfs와 bfs 어떤 방식으로도 풀 수 있다고 생각하여 더 편한 dfs로 첫 시도를 진행하였는데 잘못된 접근인 걸 알고 bfs로 진행하였습니다. (깊이가 한번 깊어질 때  +하루가 되어야 하므로 bfs로 푸는 것이 알맞다고 생각함)
그래프가 단방향인지 양방향인지에 따라 달라지므로 확인하자!
=> [Week05] BOJ 그래프 탐색 알고리즘 - 5문제 완료

JeonHyoChang/week_05/BOJ_1012_유기농배추.py, JeonHyoChang/week_05/BOJ_2606_바이러스.py, JeonHyoChang/week_05/BOJ_260_DFS와BFS.py
- 맵으로 만들어서 진행하면 따로 방문 여부를 탐색을 안해도 되나 했는데 뒤로 갈수록 이런 꼼수(?)는 안통하더군요 ㅠㅠ
- 초기 방식은 맵으로 구성 하고 연결 여부를 set으로 묶어 경로를 더해가는 방식으로 구현
- 후기 방식은 방문여부에 따른 True/False 를 부여해 dfs 방식을 활용하여 풀이
- 뭔가 새로운 방식을 발견한것 같은 생각으로 오기를 부려 이상한 방법으로 풀이를 진행 하니 힘들더군요... 몸도, 정신도, 시간도 ㅋㅋ;;
- 오늘 몸상태가 별로라서 진행을 빨리 못했습니다 ㅠㅠ 수요일 까지 5번 문제 풀이하도록 노력할게요!!!!
=> [Week 05] BOJ 그래프 탐색 알고리즘 - 4문제 완료

JeonHyoChang/week_06/BOJ_01_9372_상근이의여행.py, JeonHyoChang/week_06/BOJ_02_20364_부동산다툼.py, JeonHyoChang/week_06/BOJ_03_9934_완전이진트리.py, JeonHyoChang/week_06/BOJ_04_1991_트리순회.py, JeonHyoChang/week_06/BOJ_05_5639_이진검색트리.py
- 일요일 부터 계속해서 식중독 때문에 고생했습니다 ㅠㅠㅠㅠ, 늦었지만 간신히 올립니다 ㅠㅠ, 먹는거 조심하세요
- 파이썬이라서 객체를 만드는게 자바만큼은 아니여서 맵으로 해서 풀었습니다. 딱히 문제 풀이에 지장은 없더군요 ㅋㅋ
- 상근이 문제 너무 날로 풀어서 조금 마음에 걸리는군요;;
- 1-3번: 선으로 연결되어있는 방식의 문제라서 트리로 접근해서 플었지만 조건이 너무 널럴해서 일부 축약해서 풀이(4,5번에 비해)
- 4번: 이진 트리 구조를 만족하면서 풀기위해 map 을 활용하여 풀이
- 5번: 전위순회 구조의 특징을 활용하여 map으로 변환 & 변환한 map을 4번의 후위순회 방식을 가져와 출력
- 아직까지는 이진 트리만 나오는 문제라서 문제를 푸는 접근방법이 생각보다 쉬웠다는 느낌을 받았습니다.
- 전,중,후 위 출력하는 알고리즘 하나 작성하고 돌려쓰니 편하군요 ㅋㅋㅋ
- 4번 문제부터 본격적인 트리 문제라는 느낌을 받았습니다. 이전까지는 다른 방식으로 해도 되는 느낌이여서 ㅋ
- 디버그 모드 잘쓰면 매우 좋습니다!!
=> [Week06] BOJ 트리 알고리즘 - 5문제 완료

jinny-l/week_06/BOJ_20364_부동산_다툼.java, jinny-l/week_06/BOJ_9372_상근이의_여행.java
스프링 프로젝트 시작하면서 시간 관리가 너무 안되고 있네요 ㅠㅠ
이번주는 2문제만 풀고 제출합니다.
못푼 문제는 코쿼 방학기간에 보충하도록 하겠습니다.
죄송합니다...
=> [Week 06] BOJ 트리 알고리즘 - 2문제 완료

jaea-kim/week_06/BOJ_1991_트리순회.java, jaea-kim/week_06/BOJ_20364_부동산다툼.java, jaea-kim/week_06/BOJ_9372_상근이의여행.java, jaea-kim/week_06/BOJ_9934_완전이진트리.java
* 트리에 대해 공부를 하고 문제를 풀었는데 노드를 만드는 것이 어려웠습니다. 
* `완전이전트리` 문제에서 머리 속에서는 트리가 있는데ㅋㅋ 어떻게 순회하는지도 있는데.. 구현으로 옮기는게 너무 어려웠습니다ㅠㅠ 
저는 지금까지 주제 중에 이번 주제가 제일 어려웠습니다...
늦어서 죄송합니다...
=> [Week6] BOJ 트리 알고리즘 - 4문제 완료

HyowonSin/week_08/BOJ_11053_가장긴증가하는부분수열.java, HyowonSin/week_08/BOJ_1149_RGB거리.java, HyowonSin/week_08/BOJ_11660_구간합구하기5.java, HyowonSin/week_08/BOJ_12865_평범한배낭.java, HyowonSin/week_08/BOJ_9095_123더하기.java
생각 보다 많이 막혀서 힌트를 많이 찾아봤습니다.
DP 테이블을 만들기 위한 규칙을 찾는 것이 관건인 것 같습니다.
종이에 나열해보고 그려보면서 끄적대는 것이 좋은 것 같습니다.
문제가 주어질 때 부터 2차원 배열을 쓰는 것은 DP 테이블도 2차원으로 만들겠지만
하나의 배열만 주어지는 경우에도 DP 테이블을 2차원으로 만드는 생각도 잘 해야할 것 같습니다.
최대/최소를 찾는 건 앞에서 부터 갱신하며 채워나가는 것 같고
가짓수나 구간 합 처럼 특정 값을 찾는 건 N번째 항의 규칙을 찾아야 하는 것 같은데
아직은 문제를 몇 개 안 풀어봐서 잘 모르겠습니다.
개인적으론 1, 2 번이 3, 4번 보다 힘들었습니다.
사실 풀이를 봐도 어떻게 이 방법이 모든 고려 사항을 커버하나 싶은 것도 있었습니다.
일단 코테를 위해서는 그냥 문제를 많이 풀어서
어느 정도 유형을 익히는 것이 효율적일 것 같습니다.
또 구간 합 문제나 이번 네이버 코테에서도 느꼈는데
문제를 꼼꼼하게 잘 읽어야 할 것 같습니다.
=> [Week 08] 백준 DP 알고리즘 - 5문제 완료

jaea-kim/week_08/BOJ_11053_가장긴증가하는부분수열.java, jaea-kim/week_08/BOJ_1149_RGB거리.java, jaea-kim/week_08/BOJ_11660_구간구하기.java, jaea-kim/week_08/BOJ_9095_123더하기.java
이번 주제가 제일 어려웠다. 점화식을 찾으라는데,, 어떻게 찾아야 할지 감도 안 오는 것들이 많았다. 
마지막에 올 수 있는 것을 생각하고 밑으로 찾아 내려가는 방식이 조금 더 쉽게 접근할 수 있는 것 같은 느낌적인 느낌만 든다,,
DP 문제들은 더 풀어봐야 알 것 같다
=> [Week 08] 백준 DP 알고리즘 - 추가 제출 4문제 완료

JeonHyoChang/week_08/BOJ_01_9095_1,2,3더하기.py, JeonHyoChang/week_08/BOJ_02_11053_가장긴증가하는부분수열.py, JeonHyoChang/week_08/BOJ_03_11660_구간합구하기5.py, JeonHyoChang/week_08/BOJ_04_1149_RGB거리.py
DP 너무 어려웠습니다 ㅠㅠㅠ
마지막 문제를 만족스럽게 완료하지 못해 너무 아쉽습니다ㅠㅠ 다음에 완료해서 제출 꼭 하겠습니다!!
+ DP문제 많이 풀어봐야겠음을 뼈저리게 느낍니다....
=> [Week 08] 백준 DP 알고리즘 - 4문제 완료(추가 제출)

jinny-l/week_08/BOJ_11053_가장_긴_증가하는_부분_수열.java, jinny-l/week_08/BOJ_1149_RGB거리.java
- 구간 합 구하기 문제에서 예시로 "(2, 2)부터 (3, 4)까지 합을 구하면 3+4+5+4+5+6 = 27"라고 하는데
왜 "3+4+5+`3`+4+5+6" 이 아닌지 이해를 못했습니다.
- 1,2,3 더하기 문제에서 점화식을 이해못했습니다.
dp[n] = dp[n-1] + dp[n-2] + dp[n-3]
- 예를 들어 8이면, n-4까지 존재하는데 제가 뭔가를 잘못 이해한 것 같습니다.
- 1 + 7
- 2 +6
- 3 + 5
- 4 + 4
=> [Week 08] BOJ DP 알고리즘 - 2문제 완료

Gwonwoo-Nam/week_09/BOJ_11000_강의실배정.py, Gwonwoo-Nam/week_09/BOJ_11399_ATM.py, Gwonwoo-Nam/week_09/BOJ_1931_회의실배정.py, Gwonwoo-Nam/week_09/BOJ_20115_에너지드링크.py, Gwonwoo-Nam/week_09/BOJ_21314_민겸수.py
파이썬으로 넘어가느라 아주 힘들었습니다.. 하루종일 알고리즘만 푼 것 같네요
뒤에 두 문제가 어려웠는데 유튜브 참고했습니다.. 
밑에 증명도 있다고 하는데 한번 보고 스터디때도 논의해보면 좋을 것 같습니다.
[그리디 유튜브 해설](https://www.youtube.com/watch?v=7noZLdfHIMQ&t=918s)
[그리디 최적해 증명](https://www.youtube.com/watch?v=vw4gqeM4UGs)
=> [Week09] BOJ 그리디 알고리즘 - 5문제 구현

Gwonwoo-Nam/week_10/듣보잡.py, Gwonwoo-Nam/week_10/문자열게임2.py, Gwonwoo-Nam/week_10/싸이버개강총회.py, Gwonwoo-Nam/week_10/파일정리.py, Gwonwoo-Nam/week_10/회문.py
- Two Pointer를 활용해서 로직을 세우면 시간 복잡도를 단축할 수 있는 문제가 있었습니다.
- 파이썬이 쉽긴하지만 사용하는 라이브러리의 시간복잡도를 잘 이해해야할 것 같습니다. 제 경우는 슬라이싱으로 스트링에서 한 글자를 삭제시켰는데 slicing은 모든 글자를 복사해서 새로운 스트링을 만들기 때문에 길이가 n인 문자열은 시간복잡도가 O(n)입니다.
- 중복 찾기 -> 브루트 포스 대신 set 활용하면 시간 복잡도를 조금 개선할 수 있었습니다.
=> [Week 10] BOJ 문자열 알고리즘 - 5문제 완료

HyowonSin/week_10/BOJ_17609_회문.py, HyowonSin/week_10/BOJ_1764_듣보잡.py, HyowonSin/week_10/BOJ_19583_싸이버개강총회.py, HyowonSin/week_10/BOJ_20291_파일정리.py, HyowonSin/week_10/BOJ_20437_문자열게임2.py
좀 쉽다 생각하니 보통 시간초과가 났습니다.
그래서 이중 for문을 다 돌지 않도록 하는 편으로 진행했습니다.
방법은 여러가지 있는 것 같습니다.
문자열의 대소비교는 아스키코드 값을 한칸씩 비교한다고 합니다.
set 의 입력은 O(1) 의 시간 복잡도
sys 의 readline() 은 마지막에 \n 을 같이 가져와서 공백 제거가 필요
그리고 마지막 readline() 에 종료 문자? 가 있는지 len(str) 이 1이 나오는 것 같습니다.
필터에 람다 돌리고 그러는 게 그냥 반복문 2번 보다 속도가 느린 것 같습니다
str = str[1:len(str)-1] 이런 식으로 하다가 시간 초과가 났습니다.
골드5 회문 틀렸는데 초등부 문제라 좀 타격이 큽니다.
양 끝에서 처리하면서 들어오니까 왼쪽, 오른쪽 경우가 나뉩니다.
가운데를 잡아서 양 끝으로 나가야 할 것 같습니다.
=> [Week 10] BOJ 문자열 알고리즘 - 4문제 완료 / 1문제 실패

jinny-l/week_10/BOJ_1764_듣보잡.java, jinny-l/week_10/BOJ_19583_싸이버개강총회.java, jinny-l/week_10/BOJ_20291_파일_정리.java, jinny-l/week_10/BOJ_20437_문자열_게임_2.java
- List를 사용해서 contains로 확인하니 시간 초과 났습니다.
- 찾아보니 HashSet의 contains()는 O(1), ArrayList의 contains()는 O(n)의 시간 복잡도를 갖고 있었습니다.
- 참고: https://www.baeldung.com/java-hashset-arraylist-contains-performance
- 처음에 SimpleDateFormat으로 풀었는데 시간 초과했습니다.
- 찾아보니 문자열 형식이 똑같기 때문에 compareTo로 비교해서 풀었습니다.
- 터미널에 값 입력 후 EOF을 어떻게 표현할지 찾아보니 값 입력 후 커맨드 + D를 누르면 되었습니다.
- 매우매우 화납니다.
- 찾아보니 블로그랑 똑같이 풀었는데 어디서 틀렸는지 모르겠습니다.
---
아 이제 여러분은 파이썬 사용해서 이런 내용 필요없으시죠...?
=> [Week 10] BOJ 문자열 알고리즘 - 3문제 완료 / 1문제 실패

jinny-l/week_13/BOJ_1913_달팽이.java, jinny-l/week_13/BOJ_20436_ZOAC_3.java
=> [week13] BOJ 구현 알고리즘 - 2문제 완료

HyowonSin/week_11/BOJ_16719_ZOAC.py, HyowonSin/week_11/BOJ_1913_달팽이.py, HyowonSin/week_11/BOJ_20207_달력.py, HyowonSin/week_11/BOJ_20436_ZOAC3.py, HyowonSin/week_11/BOJ_22856_트리순회.py
구현은 말 그대로 구현인 것 같습니다.
문제를 잘 읽는 게 중요한 것 같습니다.
구현은 어려워지면 답도 없는 것 같습니다.
반례 찾기가 어려워요..
그리고 단순하게 구현하면
풀리긴 하는데 속도가 느려지는 것 같습니다.
=> [Week 13] BOJ 구현 알고리즘 - 4문제 완료/1문제 시간 초과

jaea-kim/week_13/BOJ_16719_ZOAC.py, jaea-kim/week_13/BOJ_1913_달팽이.py, jaea-kim/week_13/BOJ_20207_달력.py, jaea-kim/week_13/BOJ_20436_ZOAC3.py, jaea-kim/week_13/BOJ_22856_트리순회.py
어려웠어요.. 
구현 어려워요...
시간이 너무 없어요.. 눈물나요..
=> [Week13] BOJ 구현 알고리즘 - 4문제 완료 

jinny-l/week_14/BOJ_1074_Z.java, jinny-l/week_14/BOJ_17829_222_풀링.java, jinny-l/week_14/BOJ_2630_색종이_만들기.java
재귀로 푸는 문제가 익숙하지 않고 어렵게 느껴집니다.
재귀로 돌때 헷갈리지 않게 익숙해져야 겠습니다.
=> [Week 14] BOJ 분할 정복 알고리즘 - 3문제 완료

jinny-l/week_15/BOJ_1935_후위_표기식2.java, jinny-l/week_15/BOJ_2493_탑.java, jinny-l/week_15/BOJ_9012_괄호.java
- 자바 코드로 스택을 자주 써보지 않았는데, 문제를 풀면서 사용법을 익힐 수 있었습니다.
- 프로그래머스에서 괄호랑 똑같은 문제가 있었는데, 이전에는 왼쪽, 오른쪽 괄호 개수를 카운팅하여 풀었고 이번에는 스택을 활용해 풀었습니다.
- 탑 문제 같은 경우, 아직까지 문제만 보고 스택을 떠올리기는 힘들었습니다.
=> [Week 15] BOJ 자료구조 - 3문제 완료

HyowonSin/week_15/BOJ_1935_후위표기식2.py, HyowonSin/week_15/BOJ_2493_탑.py, HyowonSin/week_15/BOJ_9012_괄호.py
자료 구조 문제집이기 때문에 스택을 쓰게 됐는데
다른 방법도 풀릴 문제들이긴 했던 것 같습니다.
큐를 리스트로 만드는 것과 링크드 리스트로 만드는 것을 잘 구별해서 사용하면 좋을 것 같습니다.
자료 구조를 공부할 때는 시간 복잡도를 계산하는 연습을 같이 하면 좋을 것 같습니다.
for 문에 else 를 붙여보면 좋을 것 같았습니다.
탑 문제에 우선순위 큐를 생각해 봤던 김에
그대로 써봤는데 속도가 무지 느립니다.
=> [Week 15] BOJ 자료구조 1 - 3문제 완료

jaea-kim/week_16/BOJ_1620_나는야포켓몬.py, jaea-kim/week_16/BOJ_2075_N번째큰수.py
=> [Week 16] BOJ 자료구조 2 - 2문제 완료

JeonHyoChang/week_16/BOJ_01_1620_나는야포켓몬마스터이다솜.py, JeonHyoChang/week_16/BOJ_02_2075_N번째큰수.py, JeonHyoChang/week_16/BOJ_03_7662_이중우선순위큐.py
- 2번까지 풀만했는데 3번문제 선넘는군요 ㅋㅋㅋㅋ
- 힌트 보고 간신히 풀었습니다 ㅠㅠㅠ 너무 시간초과 조건이 빡빡하더군요 ㅠ
=> [Week 16] BOJ 자료구조 2 - 3문제 완료

jaea-kim/week_17/BOJ_15649_N과M.py, jaea-kim/week_17/BOJ_15663_N과M9.py
=> [Week17] BOJ Backtracking - 2문제 완료

JeonHyoChang/week_17/BOJ_01_15649_N과M(1).py, JeonHyoChang/week_17/BOJ_02_15663_N과M(9).py, JeonHyoChang/week_17/BOJ_03_14712_ 넴모넴모(Easy).py
이사하느라 힘들었습니다.... 오기전에 마지막 풀었는데 시간초과 나네요 ㅠㅠ
파이썬이라서 시간 초과 납니다 ㅋㅋ;;;
=> [Week17] BOJ Backtracking - 2문제 완료 + 1문제 완료 못함

JeonHyoChang/week_18/BOJ_01_18352_특정거리의도시찾기.py, JeonHyoChang/week_18/BOJ_02_11403_경로 찾기.py, JeonHyoChang/week_18/BOJ_03_13549_ 숨바꼭질3.py
=> [Week21] BOJ Shortest Path - 2문제 완료 + 1문제 X 

JeonHyoChang/week_22/BOJ_01_1197_최소스패닝트리.py, JeonHyoChang/week_22/BOJ_02_1922_네트워크연결.py, JeonHyoChang/week_22/BOJ_03_21924_도시걸설.py
사실상 하나의 로직으로 3문제가 풀이가 되는것이 좀 아쉬웠습니다.
로직에 도달하는것이 어렵지만 이해한다면 다른 문제에도 적용할수 있을것 같아 기대 됩니다 ㅎㅎ
=> [Week 23] BOJ 시뮬레이션 - 3문제 완료

jinny-l/week_22/BOJ_1197_최소_스패닝_트리.java, jinny-l/week_22/BOJ_1922_네트워크_연결.java, jinny-l/week_22/BOJ_21924_도시_건설.java, jinny-l/week_23/BOJ_1713_후보_추천하기.java, jinny-l/week_23/BOJ_5212_지구_온난화.java
Git이 이래저래 문제가 많아 임의로 오가니제이션에 브랜치 따서 PR 올렸습니다.
다음주까지 꼭 수정하겠습니다 🥲
=> [Week22~23] MST 3문제 + Simulation 2문제

JeonHyoChang/week_24/LTC_01_238.py, JeonHyoChang/week_24/LTC_02_2300.py, JeonHyoChang/week_24/LTC_03_10.py
2문제까지는 풀었는데 마지막 문제 시간초과 납니다 ㅠㅠㅠ
풀이를 봐도 같은 재귀인데 어째서....
=> [Week24] 2문제 완료

HyowonSin/season2/_230811/BOJ_3190_뱀.py
접근 까진 괜찮았던 것 같은데..
중간 중간 문제가 많았다 ㅠㅠ
꼬리를 착각했다가 만주가 큐쓰면 좋대서 큐를 쓰니까 쉽게 풀렸다.
맵 그릴 때 제대로 보기.. +1 차이로 못 찾아서 고생했다.
너무 지저분하게 푼 것 같다.
=> [230811] BOJ 뱀 - 1문제

JeonHyoChang/Season2/23.08.16 카카오 2문제/실패율.py, JeonHyoChang/Season2/23.08.16 카카오 2문제/후보키.py, JeonHyoChang/Season2/23.08.25 카카오 2문제/두 개 뽑아서 더하기.py, JeonHyoChang/Season2/23.08.25 카카오 2문제/문자열 압축.py
2번문제를 잘못접근해서 시간이 좀 걸린것이 아쉽습니다 ㅠㅠ
+ 포로의 조언을 수용해서 이제 슬슬 IDE 없이 코딩하는 연습을 하도록 하겠습니다!!!
=> [230816] PGS 실패율, 후보키 - 2문제

JeonHyoChang/Season2/23.08.16 카카오 2문제/실패율.py, JeonHyoChang/Season2/23.08.16 카카오 2문제/후보키.py, JeonHyoChang/Season2/23.08.25 카카오 2문제/두 개 뽑아서 더하기.py, JeonHyoChang/Season2/23.08.25 카카오 2문제/문자열 압축.py
오늘은 힐링 느낌으로 1, 2 단계 문제를 풀이했습니다 ㅎㅎ
=> [230825] PGS (두 개 뽑아서 더하기, 문자열 압축) - 2문제
